# Generated by Django 6.1 on 2026-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_timesheettemplate_timesheetrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMarginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_margin', models.DecimalField(decimal_places=2, default=0, help_text='Time margin for SD (hours).', max_digits=6)),
                ('atisa_margin', models.DecimalField(decimal_places=2, default=0, help_text='Time margin for ATISA (hours).', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'time margin settings',
                'verbose_name_plural': 'time margin settings',
            },
        ),
    ]
